In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc - tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()
print(c)
print("For loop:" + str(1000*(toc - tic)) + "ms")

249971.31626869598
Vectorized version:1.3699531555175781ms
249971.31626868306
For loop:1134.9360942840576ms


In [3]:
A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
print(A)


[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = A.sum(axis=0) # axis = 0 --> sum vertically every column
print(cal)

[ 59.  239.  155.4  76.9]


In [5]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)


[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [6]:
a = np.random.randn(5)

In [7]:
print(a)

[ 0.67443401 -0.00663514  1.65230304 -1.13905744 -1.68265029]


In [8]:
print(a.shape)

(5,)


In [9]:
print(a.T)

[ 0.67443401 -0.00663514  1.65230304 -1.13905744 -1.68265029]


In [10]:
print(np.dot(a,a.T))

7.313774459014599


In [11]:
a = np.random.randn(5,1)
print(a)

[[-0.38882088]
 [-1.00704608]
 [ 1.03646811]
 [-1.28136473]
 [ 0.72212292]]


In [12]:
print(np.dot(a,a.T))

[[ 0.15118168  0.39156054 -0.40300044  0.49822136 -0.28077647]
 [ 0.39156054  1.0141418  -1.04377114  1.29039333 -0.72721106]
 [-0.40300044 -1.04377114  1.07426614 -1.32809368  0.74845738]
 [ 0.49822136  1.29039333 -1.32809368  1.64189557 -0.92530284]
 [-0.28077647 -0.72721106  0.74845738 -0.92530284  0.52146151]]


In [13]:
a = np.zeros((32,32,3))
x = a.reshape((32*32*3),1)
print(x)
print(x.shape)

[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]
(3072, 1)


In [14]:
a = np.random.rand(4,3)
b = np.random.rand(3,2)
c = np.dot(a,b)
print(c.shape)
# c = a*b
# print(c.shape)

(4, 2)


In [15]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print(c)
print(c.shape)
print(a - a)

[[-1.2758719  -1.33751618  1.5332351 ]
 [-0.07068263 -0.12088397 -0.04658116]
 [-0.72686023  0.7580049  -0.25165006]]
(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
m = 5
X = np.random.randn(5,10)
Y = np.random.randn(1,10)
A = np.random.randn(1,10)
dw = (1/m) * (np.dot(X,(A - Y).T))
print(dw)

[[ 0.68146648]
 [-0.14417274]
 [-2.29774813]
 [-0.71649933]
 [-0.7922579 ]]


In [17]:
A = np.random.randn(4,3)
B = np.sum(A, axis = 1, keepdims = True)
print(B.shape)


(4, 1)
